// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rchhtwyqgaauvuhmllur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjaGh0d3lxZ2FhdXZ1aG1sbHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzI1MzAsImV4cCI6MjA2MDgwODUzMH0.y5NyIeH-ICFsbIJEHO4G71IrvBIJPJ17iuZLzpig0DA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);